---
dependency:
  name: galaxy
driver:
  name: docker
scenario:
  name: default
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: fail2ban-debian-10
    image: debian:10
    command: /lib/systemd/systemd
    privileged: true
  - name: fail2ban-debian-9
    image: debian:9
    command: /lib/systemd/systemd
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: profile_tasks
      jinja2_extensions: jinja2.ext.do
      gather_timeout: 30
      timeout: 30
    ssh_connection:
      pipelining: true
  inventory:
    group_vars:
      all:
        fail2ban_ignoreip:
          - a.host.name
          - 1.2.3.4/32
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
