---
- name: Prepare
  hosts: all
  become: true
  tasks:
    - name: touch logfiles to avoid fail2ban startup failure in container
      file:
        path: "{{ item }}"
        state: touch
      loop:
        - /var/log/auth.log
        - /var/log/mail.log
